### ISSUE TITLE
 Disconnecting in Whatsapp Connected Devices does not identify reason and tries to reconnect 

### ISSUE THREAD

**Issue by AashishAnand02** [lyfe00011/whatsapp-bot#17]
![image](https://user-images.githubusercontent.com/99354930/153274959-95d4e68a-c868-413d-92ed-7f657b02d8c5.png)
bailey got disconnected and now the bot is not working and the in the logs showing connection failed.

**Comment by lyfe00011** [comment]
> ![image](https://user-images.githubusercontent.com/99354930/153274959-95d4e68a-c868-413d-92ed-7f657b02d8c5.png) bailey got disconnected and now the bot is not working and the in the logs showing connection failed.

restart dyno or change session https://github.com/lyfe00011/whatsapp-bot/wiki/FAQ#what-do-if-i-logout-or-changed-whatsapp-
