### ISSUE TITLE
can't scan the  qr code 

### ISSUE THREAD

**Issue by shan978** [lyfe00011/whatsapp-bot#27]
WhatsApp didn't scan the qr code , now what to do >?>?>>
![Screenshot_20220417-083450_WhatsApp](https://user-images.githubusercontent.com/96291655/163698491-e193568e-abdd-4590-9dfc-90a4e4f96531.jpg)

**Comment by lyfe00011** [comment]
> WhatsApp didn't scan the qr code , now what to do >?>?>> ![Screenshot_20220417-083450_WhatsApp](https://user-images.githubusercontent.com/96291655/163698491-e193568e-abdd-4590-9dfc-90a4e4f96531.jpg)

https://github.com/lyfe00011/wa-bot
