### ISSUE TITLE
.tagall

### ISSUE THREAD

**Issue by ekomic** [lyfe00011/whatsapp-bot#49]
I thought tag will only notify groups members without dropping all names of members in the group. 
![Screenshot_20220925-222159_WhatsApp](https://user-images.githubusercontent.com/30246127/192166171-b6389daa-b02b-4758-af1a-507ed02df299.jpg)

**Comment by lyfe00011** [comment]
> I thought tag will only notify groups members without dropping all names of members in the group. ![Screenshot_20220925-222159_WhatsApp](https://user-images.githubusercontent.com/30246127/192166171-b6389daa-b02b-4758-af1a-507ed02df299.jpg)

Use tag
